### ISSUE TITLE
[hardknott] broken link with Xerces-J recipe 

### ISSUE THREAD

**Issue by EnriqueSLHC** [meta-java/meta-java#10]
I cannot believe this. This not Meta-Java week.  

When trying to do a fresh 'hardknott' build, I get failed fetch for: /meta-java/recipes-core/xerces-j/xerces-j_2.11.0.bb

Another broken link.  This must just happen. The broken link is: http://archive.apache.org/dist/xerces/j/Xerces-J-src.2.11.0.tar.gz

thanks..

**Comment by lejcik** [comment]
I have the same issue, temporarily I fixed the recipe as:

```diff
-SRC_URI = "http://archive.apache.org/dist/xerces/j/Xerces-J-src.${PV}.tar.gz"
+SRC_URI = "http://ftp.deu.edu.tr/pub/Infosystem/Apache/xerces/j/source/Xerces-J-src.${PV}.tar.gz"
```

It occurs also on branch `kirkstone`, so I'd appreciate fixing the issue in other branches as well, thanks.

**Comment by moto-timo** [comment]
Apache has moved to a new [FQDN](https://dlcdn.apache.org//xerces/j/source/). However, only `2.12.2` is available. We should seriously consider upgrading and backporting the upgrade (there may be some vulnerabilities).

**Comment by moto-timo** [comment]
I just checked the [archives](https://archive.apache.org/dist/xerces/j/source/) URL and [2.11.0](https://archive.apache.org/dist/xerces/j/source/Xerces-J-src.2.11.0.tar.gz) is still available.

**Comment by tjpsantiago** [comment]
hi,

will dunfell also be updated? it also has this broken link.

**Comment by moto-timo** [comment]
hardknott (which is long EOL) merged in https://github.com/meta-java/meta-java/commit/ca397f38fca7d83ae0a4b57980164e2f91d527b8
