### ISSUE TITLE
rhino-native-1.7r4-r0 do_fetch: Fetcher failure for URL: 'https://github.com/downloads/mozilla/rhino/rhino1_7R4.zip'. Unable to fetch URL from any source

### ISSUE THREAD

**Issue by saswatinayak** [meta-java/meta-java#16]
getting stuck in error 

ERROR: rhino-native-1.7r4-r0 do_fetch: Fetcher failure for URL: 'https://github.com/downloads/mozilla/rhino/rhino1_7R4.zip'. Unable to fetch URL from any source.
ERROR: rhino-native-1.7r4-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in:....build/tmp/work/x86_64-linux/rhino-native/1.7r4-r0/temp/log.do_fetch.28909
ERROR: Task (virtual:native:...sources/poky/../meta-java/recipes-core/rhino/rhino_1.7r4.bb:do_fetch) failed with exit code '1'

Can anyone help ?

**Comment by rymssa** [comment]
Check #7

**Comment by g0hl1n** [comment]
merged #7, should therefore be fixed.

Thanks for reporting the issue!
