### ISSUE TITLE
[kirkstone] rhino needs backport from master to kirkstone

### ISSUE THREAD

**Issue by jmillscnhind** [meta-java/meta-java#24]
Building rhino on kirkstone fails to fetch the code. 
In my local I backported(from master via a bbappend) and rhino passes.

**Comment by moto-timo** [comment]
The series from master was merged:
https://github.com/meta-java/meta-java/commit/6cf1a3e210631fd3c5814cacb9daa5ec8b23983d
https://github.com/meta-java/meta-java/commit/68e8fdef3af52d36a3b016cea9f7a5eb0d0bdc39
https://github.com/meta-java/meta-java/commit/cb488b8dcb8db1f3d3d00bb25bd5b269fd7af833
