### ISSUE TITLE
icedtea7-native_2.1.3.bb Compilation issue SEGFAULT - in OPENSUSUE 

### ISSUE THREAD

**Issue by tanginik** [meta-java/meta-java#26]
![image](https://github.com/meta-java/meta-java/assets/141885680/c97a125c-f836-4812-b2af-371a323d0aa6)

**Comment by buonan** [comment]
Any updates?

**Comment by moto-timo** [comment]
This is affecting any Linux distribution with gcc-11 or greater. This probably means the very ancient icedtea7-native version needs to be bumped to one which fixes whatever is causing the segfault.

There is no mythical pool of developers waiting to fix issues here. This is an open source community layer. If you are willing to dig into an update to a newer version of icedtea7-native, please send a pull request.

**Comment by moto-timo** [comment]
@tanginik is this possibly resolved by the suggestion in https://github.com/meta-java/meta-java/issues/18#issuecomment-1914620702 ?

**Comment by moto-timo** [comment]
@tanginik @buonan which version of OpenSUSE are you using? latest https://get.opensuse.org/leap/15.5/ ?

**Comment by buonan** [comment]
I tried the fix mentioned in https://github.com/meta-java/meta-java/issues/18#issuecomment-1914620702 and it has fixed my error.  I am using Yocto v3.3.6 with meta-raspberrypi (hardknott) and meta-java (dunfell-next).

**Comment by buonan** [comment]
My host is WSL2 Debian and my gcc is Debian (12.2.0-14) hope this helps!  

Okay got it, thanks for the tips!

**Comment by fabioestevam** [comment]
Hi @moto-timo'

I observe the same icedtea7-native_2.1.3.bb build failure in kirkstone. 

kirkstone-next builds fine. Could you please merge kirkstone-next into kirkstone to fix the problem?

**Comment by moto-timo** [comment]
Everyone is ignoring that the specific point of this Issue was that it affected OpenSUSE (at a non-reported version). Closing as I have pushed to kirkstone.

**Comment by moto-timo** [comment]
https://github.com/meta-java/meta-java/discussions/25

OpenSUSE 15.3
