### ISSUE TITLE
Broken download link for rhino

### ISSUE THREAD

**Issue by camm73** [meta-java/meta-java#4]
The `do_fetch` job for rhino is failing. Going to the link in the recipe [https://github.com/downloads/mozilla/rhino/rhino1_7R4.zip](https://github.com/downloads/mozilla/rhino/rhino1_7R4.zip) returns 502 status code with message "Error downloading file".

On the Github page for Rhino, there is a release titled [Rhino1_7R4_RELEASE](https://github.com/mozilla/rhino/releases/tag/Rhino1_7R4_RELEASE). It has a download link for the source zip file which works: https://github.com/mozilla/rhino/archive/refs/tags/Rhino1_7R4_RELEASE.zip

While it's tagged as the same version, the sha256 of the zip file is different than the one listed in the recipe. Unfortunately I don't have the zip file from the original link to be able to run a diff on the contents

**Comment by cambesol** [comment]
I am also blocked on this. I do have a version (with the correct MD5 hash) which I could use, but need a clean build for a release without manual intervention. Is there any progress?

**Comment by g0hl1n** [comment]
resolved by #7
