### ISSUE TITLE
[hardknott] Java Rhino Recipe Fix be backported

### ISSUE THREAD

**Issue by EnriqueSLHC** [meta-java/meta-java#8]
We have a major project that is dependent on 'hardknott' revision of bitbake.  It would be greatly appreciated if the fix for Rhino would be ported to hardknott.  I was unsuccessful to append the changes that were made to the master branch, into the current hardkot branch. One would think it would be simple to append these changes.

**Comment by g0hl1n** [comment]
@EnriqueSLHC can you please test if #9 works for you?

**Comment by EnriqueSLHC** [comment]
I found another broken link in a different recipe.  let me append this one and give it a try again.
